"""enum addded

Revision ID: 2a49acbc5229
Revises: 1873b5cf0e21
Create Date: 2026-04-30 05:01:09.194151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a49acbc5229'
down_revision: Union[str, Sequence[str], None] = '1873b5cf0e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'productdetail', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productdetail', type_='unique')
    # ### end Alembic commands ###
