"""add product detail

Revision ID: 410c790d3d13
Revises: 4cd0c5cc627c
Create Date: 2026-04-18 14:54:38.886821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '410c790d3d13'
down_revision: Union[str, Sequence[str], None] = '4cd0c5cc627c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productdetail', sa.Column('rating', sa.Numeric(precision=10, scale=1), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productdetail', 'rating')
    # ### end Alembic commands ###
