"""commit stock

Revision ID: 8b0f9d628cb1
Revises: 410c790d3d13
Create Date: 2026-04-18 14:56:02.917044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0f9d628cb1'
down_revision: Union[str, Sequence[str], None] = '410c790d3d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productdetail', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productdetail', 'stock')
    # ### end Alembic commands ###
