"""delete in_stock

Revision ID: a6740151d8c5
Revises: 99ab14fea7bf
Create Date: 2026-03-11 06:53:32.454205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6740151d8c5'
down_revision: Union[str, Sequence[str], None] = '99ab14fea7bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'in_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
